INSERT INTO users(username,first_name,last_name)  VALUES('rojims','Rodgers','Meyer');            
INSERT INTO users(username,first_name,last_name)  VALUES('anthman','Anthony','Murray');
INSERT INTO users(username,first_name,last_name)  VALUES('jibs','Jibunor','Saka');      
INSERT INTO users(username,first_name,last_name)  VALUES('olami','Saheed','Aden');
INSERT INTO users(username,first_name,last_name)  VALUES('tobsi','Tobi','Olasimbo');
INSERT INTO users(username,first_name,last_name)  VALUES('mchenro','Henry','Osita');
INSERT INTO users(username,first_name,last_name)  VALUES('marck','Kareem','olawale');
INSERT INTO users(username,first_name,last_name)  VALUES('chizzy','Ohanaze','Chibudor');
INSERT INTO users(username,first_name,last_name)  VALUES('pastor_fm','Femi','Olorunshogo');
INSERT INTO users(username,first_name,last_name)  VALUES('sunnep','Sunday','Ichochuli');


INSERT INTO books(user_id,name,pages) VALUES(1,'Mr Bones','650');
INSERT INTO books(user_id,name,pages) VALUES(1,'Money Heist','700');                     
INSERT INTO books(user_id,name,pages) VALUES(2,'The Antman','2600');                     
INSERT INTO books(user_id,name,pages) VALUES(3,'Mystery of mullato','400');
INSERT INTO books(user_id,name,pages) VALUES(4,'Super league story','600');
INSERT INTO books(user_id,name,pages) VALUES(5,'Legend of the sica','900');
INSERT INTO books(user_id,name,pages) VALUES(6,'Game of Thrones','350');
INSERT INTO books(user_id,name,pages) VALUES(7,'Merlin','200');
INSERT INTO books(user_id,name,pages) VALUES(8,'50 shades darker','3500');
INSERT INTO books(user_id,name,pages) VALUES(9,'Forgotten Bird','4500');
INSERT INTO books(user_id,name,pages) VALUES(10,'One Hundred Years of Solitude','700');
INSERT INTO books(user_id,name,pages) VALUES(3,'Anna Karenina','3500');
INSERT INTO books(user_id,name,pages) VALUES(4,'The Stranger','9000');
INSERT INTO books(user_id,name,pages) VALUES(5,'The Brothers Karamazov','500');
INSERT INTO books(user_id,name,pages) VALUES(6,'The Odyssey','5000');
INSERT INTO books(user_id,name,pages) VALUES(7,'The Arabian Nights','970');
INSERT INTO books(user_id,name,pages) VALUES(8,'Faust, First Part','980');
INSERT INTO books(user_id,name,pages) VALUES(9,'The Man Without Qualities','3470');
INSERT INTO books(user_id,name,pages) VALUES(10,'The Trial','100');
INSERT INTO books(user_id,name,pages) VALUES(7,'Zorba the Greek','215');
INSERT INTO books(user_id,name,pages) VALUES(10,'The Great Expectation','870');
INSERT INTO books(user_id,name,pages) VALUES(8,'The Old Man and the Sea','900');
INSERT INTO books(user_id,name,pages) VALUES(7,'Journey to the End of the Night','900');